### ISSUE TITLE
Add tags directory page

### ISSUE THREAD

**Issue by Granitosaurus** [lektor/lektor-tags#16]
Right now individual pages for tags are being generated but there's no root page with all of the tags listed. 

i.e. blog.com/tags should be generated that lists all tags

**Comment by paternal** [comment]
FYI, now that version 0.5.0 is released, lektor-tags provide the necessary tools to build your own root page for tags: [example](https://ababsurdo.fr/blog/tag/):

- [contents.lr](https://framagit.org/lpaternault/ababsurdo/-/blob/main/content/blog/tag/contents.lr)
- [tagcloud-block.ini](https://framagit.org/lpaternault/ababsurdo/-/blob/main/flowblocks/tagcloud-block.ini)
- [template](https://framagit.org/lpaternault/ababsurdo/-/blob/main/templates/blocks/tagcloud-block.html)
