### ISSUE TITLE
Build a tag cloud

### ISSUE THREAD

**Issue by paternal** [lektor/lektor-tags#18]
Hello,
I wrote a plugin to create a tag cloud :
- [the plugin](https://framagit.org/lpaternault/ababsurdo/-/blob/9a8b6a5f37f3c13297bab375831c2c85b4582e98/packages/lektor-tag-cloud/lektor_tag_cloud.py)
- [the template producing the cloud](https://framagit.org/lpaternault/ababsurdo/-/blob/9a8b6a5f37f3c13297bab375831c2c85b4582e98/templates/blocks/tagcloud-block.html)
- [the resulting page](https://ababsurdo.fr/blog/tag/) (I suck at CSS, but you get the idea).

The plugin counts the number of articles for each tag, and attributes a "weight" to each tag, which can be a number (on [this page](https://ababsurdo.fr/blog/tag/), it is a number between 100 and 200 which is used as the text size), or a string (e.g. "small", "normal", "big", which would be used as classes), or whatever you want. The template itself is not included in the package.

Right now, it is a quick and dirty script in the git directory of the website using it. However, I would like to publish it properly.
- It is very simple and could be nicely integrated into `lektor-tags`. If you like this idea, I can write a pull request.
- If you prefer it to remain a separate plugin, I will clean it and publish it as a `lektor-tag-cloud` plugin in a few days or weeks.
Just tell me which one you want.

This could also be used to automatically generate a tags directory page (see #16).

Regards,
-- Louis

**Comment by goanpeca** [comment]
I think it could be integrated. Thoughts @runfalk @nixjdm ?

**Comment by runfalk** [comment]
I definitely think we could integrate this into lektor-tags. It makes sense provide aggregated data as part of the plugin. Two things I think are necessary to merge it:

* Don't precalculate the tag cloud unless it's used somewhere
* If it's used, don't calculate it more than once per build. I think it's really important that this feature does not affect the performance for those who don't use it.

PRs are welcome.

**Comment by paternal** [comment]
Great! I'm adding this to my TODO list.

My plan is:
- [ ] Clean and comment code.
- [ ] Turn "{{ tagweight.count }}" to a function (is a dict right now), for consistency with other weight functions.
- [ ] Write some documentation, with examples of templates.
- [ ] Don't precalculate the tag cloud unless it's used somewhere
- [ ] don't calculate it more than once per build

I might need some help for the last two items; I'll keep you updated. I do not plan to integrate a css file as an example, because I suck at CSS.

-- Louis

**Comment by paternal** [comment]
You can assign this issue to me (I don't think I'm allowed to do it myself).

**Comment by paternal** [comment]
Almost done. I am now waiting for you:
- [ ] please review #19, and answer https://github.com/nixjdm/lektor-tags/pull/19#discussion_r395984565 and https://github.com/nixjdm/lektor-tags/pull/19#pullrequestreview-378911739;
- [ ] please answer my question https://github.com/nixjdm/lektor-tags/pull/19#issuecomment-602031169;
- [ ] English is not my first language, so feel free to rephrase/rewrite my variables/comments/documentation.
